/** Shim — re-exports brand registry helpers from `@exxatdesignux/product-framework`. */

export {
  EXXAT_CORPORATE_BRAND,
  EXXAT_ACCREDITATION_BRAND,
  EXXAT_EXAM_MANAGEMENT_BRAND,
  EXXAT_STUDENT_SUCCESS_BRAND,
  EXXAT_SURVEYS_BRAND,
  EXXAT_COMPLIANCE_BRAND,
  EXXAT_CURRICULUM_MAPPING_BRAND,
  EXXAT_ONE_SITES_BRAND,
  EXXAT_PRISM_BRAND,
  EXXAT_ADMIN_BRAND,
  EXXAT_PEOPLE_BRAND,
  EXXAT_COURSES_BRAND,
  EXXAT_PROGRAMS_BRAND,
  EXXAT_PERSONNEL_BRAND,
  applyBrandColorOverride,
  brandForProduct,
  brandPreviewPanelSurfaces,
  customProductBrandConfig,
  defineProductBrand,
  getProductBrand,
  listProductBrands,
  productBrandLabel,
  registerProductBrand,
  type ProductBrandConfig,
} from "@exxatdesignux/product-framework"
