/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hjzmiwuniytbcfvjbtgj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqem1pd3VuaXl0YmNmdmpidGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Nzc1NTMsImV4cCI6MjA3MzI1MzU1M30.HdysNLa-WhSHm5Z-299pxRJnLAAfBKOUbQ1MNAHCAZc"