import { chromium } from 'playwright'
import { AxeBuilder } from '@axe-core/playwright'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } })
const pg = await ctx.newPage()
await pg.goto('http://localhost:3005/templates/tmpl1', { waitUntil: 'domcontentloaded', timeout: 30000 })
await pg.waitForTimeout(2500)
await pg.getByRole('tab', { name: /Builder/i }).click().catch(()=>{})
await pg.waitForTimeout(800)
// click the Faculty group chip to confirm it still activates (roving focus intact)
await pg.getByRole('tab', { name: /^Faculty/i }).click().catch(()=>console.log('(faculty chip click failed)'))
await pg.waitForTimeout(600)
const facultyActive = await pg.getByRole('tab', { name: /^Faculty/i }).getAttribute('data-state').catch(()=>null)
console.log('Faculty chip data-state after click:', facultyActive)
const res = await new AxeBuilder({ page: pg }).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze()
console.log('builder violations now:', res.violations.length)
res.violations.forEach(v => console.log(`  [${v.impact}] ${v.id} — ${v.help}`))
await pg.screenshot({ path: '/tmp/pce-phase15/6-builder-groups-fixed.png' })
console.log('saved 6-builder-groups-fixed')
await b.close()
