// This file exists solely so Next.js uses this root pages/ directory instead of
// src/pages/ (which is regenerated by sync-extras on every pnpm install).
// Files starting with _ are skipped by Next.js routing — no route is created.
export {}
